services:
  cron:
    container_name: ${COMPOSE_PROJECT_NAME}_cron
    build:
      context: ./
      args:
        - TIMEZONE=${TIMEZONE}
    environment:
      - TZ=${TIMEZONE}
    tty: true
    restart: ${RESTART_POLICY}
    volumes:
      - ./cron.d:/etc/cron.d
      - ./logs:/var/log/cron
